blog_index:
  path: /
  controller: App\Domain\Blog\Controller\Listing

blog_create:
  path: /create
  controller: App\Domain\Blog\Controller\Create

blog_read:
  path: /{id}/read
  controller: App\Domain\Blog\Controller\Read

blog_update:
  path: /{id}/update
  controller: App\Domain\Blog\Controller\Update

